from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from backend.orchestrator.task_decomposer import TaskDefinition


@dataclass
class ExecutionPlan:
    """Represents the execution plan generated by the planner."""

    request_text: str
    tasks: list[TaskDefinition] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "request_text": self.request_text,
            "tasks": [task.to_dict() for task in self.tasks],
            "metadata": self.metadata,
        }
