from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4

from backend.orchestrator.task_decomposer import TaskDefinition


class PlanStatus(str, Enum):
    """Aggregate status for a dependency-aware execution plan."""

    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    PARTIALLY_SUCCEEDED = "partially_succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass
class ExecutionPlan:
    """Represents the execution plan generated by the planner."""

    request_text: str
    id: str = field(default_factory=lambda: str(uuid4()))
    tasks: list[TaskDefinition] = field(default_factory=list)
    status: PlanStatus = PlanStatus.PENDING
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    finished_at: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "request_text": self.request_text,
            "tasks": [task.to_dict() for task in self.tasks],
            "status": self.status.value,
            "created_at": self.created_at,
            "finished_at": self.finished_at,
            "metadata": self.metadata,
        }
